apiVersion: v1
kind: Service
metadata:
  name: {{ include "immich.fullname" . }}-server
  labels:
    type: immich-server
    {{- include "immich.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    type: immich-server
    {{- include "immich.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "immich.fullname" . }}-ai
  labels:
    type: immich-ai
    {{- include "immich.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ai.service.type }}
  ports:
    - port: {{ .Values.ai.service.port }}
      targetPort: http-ai
      protocol: TCP
      name: http-ai
  selector:
    type: immich-ai
    {{- include "immich.selectorLabels" . | nindent 4 }}
{{- if .Values.ipp.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "immich.fullname" . }}-public-proxy
  labels:
    type: immich-public-proxy
    {{- include "immich.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ipp.service.type }}
  ports:
    - port: {{ .Values.ipp.service.port }}
      targetPort: http-ipp
      protocol: TCP
      name: http-ipp
  selector:
    type: immich-public-proxy
    {{- include "immich.selectorLabels" . | nindent 4 }}
{{- end }}
