apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "immich.fullname" . }}-server
  labels:
    type: immich-server
    {{- include "immich.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "immich.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        type: immich-server
        {{- include "immich.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "immich.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if not (empty .Values.redis.password) }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.password.name }}
                  key: {{ .Values.redis.password.key }}
            {{- end }}
            {{- if not (empty .Values.postgresql.password) }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.password.name }}
                  key: {{ .Values.postgresql.password.key }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "immich.fullname" . }}-redis-env
            - configMapRef:
                name: {{ include "immich.fullname" . }}-database-env
            - configMapRef:
                name: {{ include "immich.fullname" . }}-global-env
            - configMapRef:
                name: {{ include "immich.fullname" . }}-api-env
          ports:
            - name: http
              containerPort: {{ .Values.server.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/server/ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/server/ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.persistence.enabled }}
            {{- if and .Values.persistence.upload.enabled .Values.persistence.upload.existingClaim.name }}
            - name: upload
              mountPath: /usr/src/app/upload
            {{- end }}
            {{- if and .Values.persistence.library.enabled .Values.persistence.library.existingClaim.name }}
            - name: library
              mountPath: /usr/src/app/library
            {{- end }}
          {{- end }}
          {{- with .Values.server.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}

      volumes:
      {{- if .Values.persistence.enabled }}
        {{- if and .Values.persistence.upload.enabled .Values.persistence.upload.existingClaim.name }}
        - name: upload
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.upload.existingClaim.name }}
        {{- end }}
        {{- if and .Values.persistence.library.enabled .Values.persistence.library.existingClaim.name }}
        - name: library
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.library.existingClaim.name }}
        {{- end }}
      {{- end }}
      {{- with .Values.server.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
